### DISCUSSION TITLE
Sample code with tables

### DISCUSSION THREAD

**Discussion by pgundlach** [speedata/bagme#2] [Show and tell]
<img width="352" alt="text with table" src="https://user-images.githubusercontent.com/209434/203768479-1eedac12-a149-4928-aeaf-dcbe033950c8.png">

Using the following CSS (`styles.css`): 

```css
@font-face {
    font-family: CrimsonPro;
    src: url("fonts/crimsonpro/CrimsonPro-Regular.ttf");
}

@font-face {
    font-family: CrimsonPro;
    src: url("fonts/crimsonpro/CrimsonPro-Bold.ttf");
    font-weight: bold;
}

@font-face {
    font-family: CrimsonPro;
    src: url("fonts/crimsonpro/CrimsonPro-Italic.ttf");
    font-style: italic;
}

@font-face {
    font-family: CrimsonPro;
    src: url("fonts/crimsonpro/CrimsonPro-BoldItalic.ttf");
    font-style: italic;
    font-weight: bold;
}

body {
	font-family: CrimsonPro;
    font-size: 12pt;
    line-height: 14pt;
}

p {
    margin-top: 8pt;
    margin-bottom: 2pt;
}

.green {
    color: green;
}

#important {
    color: rebeccapurple;
    font-weight: bolder;
    font-style: italic;
}

table {
    margin-top: 20pt;
    width: 50%;
}

td {
    padding: 2pt;
    border: thick solid rgb(96, 229, 149);
}
```

The HTML file (`chunk.html`):

```html
<h1>The frog king</h1>

<p>In olden times when wishing still <em>helped</em> one,
   there lived a king whose daughters were all beautiful,
   but the <span class="green">youngest</span> was so beautiful that the sun itself,
   which has seen so much, was
   <span style="font-weight: bold">astonished</span> whenever it
   shone in her face.</p>

<p>Close by the king's castle lay a great dark forest,
	and under an old lime-tree in the forest was a well,
	and when the day was very warm, the king's child
	went out into the forest and sat down by the side of
	the cool <span id="important">fountain</span>, and when she was bored she took a
	golden ball, and threw it up on high and caught it,
	and this ball was her favorite plaything.
</p>

<table>
	<tr>
		<td rowspan="2">Hello rowspan!</td>
		<td style="vertical-align: top;">top align</td>
	</tr>
	<tr>
		<td>Hello <em>nice</em> world!</td>
	</tr>
</table>
```

and the following Go program, you should get the output above.

```go
package main

import (
	"log"
	"os"

	"github.com/speedata/bagme/document"
	"github.com/speedata/boxesandglue/backend/bag"
)

func read(filename string) string {
	b, err := os.ReadFile(filename)
	if err != nil {
		panic(err)
	}
	return string(b)
}

func dothings() error {
	d, err := document.New("out.pdf")
	if err != nil {
		return err
	}

	if d.ParseCSSString(read("styles.css")); err != nil {
		return err
	}
	wd := bag.MustSp("200pt")
	colText := bag.MustSp("20pt")
	rowText := bag.MustSp("23cm")
	if err = d.OutputAt(read("chunk.html"), wd, colText, rowText); err != nil {
		return err
	}

	return d.Finish()
}

func main() {
	if err := dothings(); err != nil {
		log.Fatal(err)
	}
}
```
